### ISSUE TITLE
Logstash Plugin for Azure Service Bus Queues

### ISSUE THREAD

**Issue by juliusl** [mspnp/semantic-logging#18]
Implement a Logstash plugin that can read from a service bus queue and pull in data.

Work Items: 
- [ ] Write .rb script.
- [ ] Test
- [ ] Write documentation for configuration.

**Comment by seanwm** [comment]
We currently have a custom logging setup that moves entries through an Azure Service Bus Queue, so I've been looking into creating something like this. I've never worked with Ruby before, but as a starting point, I assembled a very simple plugin to just retrieve messages one at a time from a Queue in a loop. In a limited way, this script works when run directly in the ruby interpreter. I've run into two issues using it with Logstash:

- The most vexing is installing the azure gem to logstash's jruby environment. There's some incompatible dependencies between the two. I've made good friends with rvm trying to massage it into place, but haven't been successful.

- The other issue is parsing the returned brokered messages. In our original setup, we were using a Dictionary<string,string> for the log entry messages, but the azure ruby gem didn't seem to be able to deserialize the (binary XML?) representation of that into a ruby object. We also tried using just a JSON string for our message body, but that still has some kind of prefix segment that's not JSON.

I've set it aside for the moment, but at this point I think it may be easiest to just use the REST API for the service bus queue directly, to avoid installing the azure gem altogether. That still leaves my brokered message parsing issues, though. Does anyone know of any documentation for their format, or (better yet) some existing ruby code for parsing brokered messages? I'd be happy to contribute whatever I get working.

As an aside, I also tried using the rabbitmq plugin, since Azure Service Bus Queues are also supposed to speak AMQP, but couldn't get that to work, either.

**Comment by jbinard** [comment]
Hi seanwm,

Unfortunately, the Azure Service Bus works with AMQP 1.0 while rabbitMQ works with AMQP 0.9.1. There is a huge difference between the two versions of the protocol, that's why it doesn't work.

**Comment by brettman** [comment]
I had the same troubles parsing messages from an azure servicebus queue using a python client.  Never got to a deep understanding of what was happening, but solved it only by creating messages with a UTF8 encoded byte stream, rather than a .net string object.  There are overloads of the BrokeredMessage ctor that allow this.  Luckily, in my case it was easier to modify the clients pushing messages instead of trying to parse out the MS serialization headers on the client.
