### ISSUE TITLE
ObservableEventListener hangs on Dispose

### ISSUE THREAD

**Issue by dkholod** [mspnp/semantic-logging#19]
I'm using the flowing code to initialize and subscribe to ObservableEventListener.

```C#
var listener = new ObservableEventListener();
            listener.EnableEvents(
            SampleEventSource.Log,
            EventLevel.LogAlways,
            Keywords.All);

            listener
                .FlushOnTrigger(entry => entry.Schema.Keywords == SampleEventSource.Keywords.Exceptions, bufferSize: 2)
                .Subscribe(new DebugObserver());

            SampleEventSource.Log.ApiTiming("test", "should_work", 1);
            SampleEventSource.Log.Exception(typeof(ArgumentException).FullName, "Wrong argument");
            listener.Dispose();
```
```C#
 public static IObservable<T> FlushOnTrigger<T>(this IObservable<T> stream, Func<T, bool> shouldFlush, int bufferSize)
 {
     return stream
    .Buffer(() => stream.SkipWhile(i => !shouldFlush(i)))
    .SelectMany(l => l.Reverse().Take(bufferSize + 1).Reverse());
}
```

It happens to hang on listener.Dispose();

With a brief investigation I've noticed that it hangs in [EventEntrySubject.cs](https://github.com/mspnp/semantic-logging/blob/master/source/Src/SemanticLogging/Observable/EventEntrySubject.cs) OnCompleted method.

```C#
public void OnCompleted()
{
            var currentObservers = this.TakeObserversAndFreeze();

            if (currentObservers != null)
            {
                Parallel.ForEach(currentObservers, observer => observer.OnCompleted());
            }
}
```
In case the parallel loop is replaced with non-parallel statement everything works well.
Before loop execution the observers collection is the flowing:
![image](https://cloud.githubusercontent.com/assets/3406251/7541002/734a088a-f5ba-11e4-8766-0d01920e2a35.png)

Please advise.

**Comment by mekoda** [comment]
Hi @dkholod, sorry for the late response.

Could you provide us a repro project where this issue can be reproduced?

**Comment by dkholod** [comment]
Hi. 
Thanks for getting back on this issue. 
I have committed unit test to demonstrate this problem.

**Comment by mhorn69** [comment]
Any news on this? I ran in the same problem.

**Comment by mekoda** [comment]
I've been taking a closer look, and I don't think this is a semantic logging issue.

This approach of buffering:

```
<stream>.Buffer(() => stream.SkipWhile(i => !shouldFlush(i)))
```

...leads to the experienced issue. 

When calling listener.Dispose(), the source stream will call OnCompleted() on all its observers. It has two, one of them being the bufferClosingSelector. When the bufferClosingSelector calls OnCompleted(), it will notify its observers for termination, in this case, the source stream, which is already terminated. Here is the issue. RX creates a new Observable and also repeats the process of notifying disposing to their observers, and in this case the target observer is already frozen. This will create a loop of creating new empty Observables with the same terminated reference and also continue with the calls.

I've tried to be brief, if more details are needed, just let me know.

Avoiding parallelism when calling OnCompleted() will solve this just because the first subscription to be completed is the one from the buffer, and right after that with no longer consider the remaining ones (generated by this buffer). However, this is just a side effect of this implementation; I think avoiding the use of the same stream will be most appropriate way to tackle this.

Other thing to consider here is the use of the **reverse + take** approach: it's really unperformant compared with the use of a circular buffer, as described [here](https://msdn.microsoft.com/en-us/library/dn774992(v=pandp.20).aspx).

**Comment by mekoda** [comment]
@mhorn69 are you using the same filter?

**Comment by mhorn69** [comment]
I am not sure what causes the problem. Right now everything works. I ran an testclient (console) with an complex app / code inside that uses Rx Extensions and a lot of async stuff and so I could not nail what causes the problem. The logging / Eventsource self was simple without anything special. It just hangs on Dispose. When I find the root cause for this I will post it here. Thanks for your support.

**Comment by mekoda** [comment]
Great, if you need some help regarding semantic logging just let us know. Moreover, feel free to reopen this issue if something similar happens.
