### ISSUE TITLE
azurewabtable logstash plugin not working

### ISSUE THREAD

**Issue by brihadish** [mspnp/semantic-logging#22]
I was trying out the azurewadtable input plugin with stdout output and i keep seeing the error 
'result not found {:level=>:warn}'. I cross checked the WADLogsTable and it is certainly receiving logs. Any idea what is causing the malfunction?

**Comment by juliusl** [comment]
That message is actually okay. It means that you don't have any more results since the last time you collected data. Take a look at the 'process' method, [lines 46-67 in azurewadtable.rb](https://github.com/mspnp/semantic-logging/blob/v3/ELK/logstash-extension/inputs/azurewadtable.rb#L46-L67). Feel free to change the message for your uses.
