### ISSUE TITLE
OutOfMemoryException when RollingFlatfFileSink is running out of disk space

### ISSUE THREAD

**Issue by svestin** [mspnp/semantic-logging#28]
Hi, I just registered at GitHub and I hope I register this issue correctly.

I just started to use Semantic Logging (and RollingFlatFile (Async mode) ) and I’m quite pleased with the functionality. However, before putting it into the production environment I performed some tests on how it would behave if running out of disk space.
I ran a small test application that creates a lot of events. I used the RollingFlatFile in Async mode and put the log files on a small usb memory stick.

I ended up with an OutOfMemoryException! More accurate, an EventSourceException (with the inner exception  OutOfMemoryException).

I’m not an expert on ETW but after a quick look in the code for RollingFlatFileSink I made some reflections:

Reflection 1:
In the OnNext method, the EventEntry always gets added to the pendingEntries collection (BlockingCollection<EventEntry>) even if the worker thread (Task: WriteEntries) some reason has terminated. Possibly it would be more robust to track if the worker thread terminates and prevent adding entries to pendingEntries (possible  clear it, to free memory as well)

Reflection 2:
In the worker thread (WriteEntries() ) all exception are caught when writing to the stream.
try
{
    this.writer.Write(formattedEntry);
} catch (Exception e)
{
    SemanticLoggingEventSource.Log.RollingFlatFileSinkWriteFailed(e.ToString());
}
However, when the stream is flushed (in the beginning of WriteEntries() ), only OperationCancelledException and ObjectDisposedException are caught. I guess there is a major risk for the worker thread to terminate if there are some other Exceptions. 

Help Needed 1:
Are there some patterns on how to manage errors and error states in Semantic Logging? In “Reflection 2“ above, errors result in the generation of event RollingFlatFileSinkWriteFailed. 
And if I understood correctly I’m supposed to call 
SemanticLoggingEventSource.Log.CustomFormatterUnhandledFault(ex.Message);
in case of error in my own TextFormatter.
Need help on the best way for my application to get aware of these errors.
In case of a GUI-application I would like to inform the user about the “disk-full error”.
In case of a server application I would like the server to send an E-mail about the “disk-full error”.

However… my main concern is the OutOfMemoryException.

Best Regards
/Stefan Vestin

**Comment by manikrish** [comment]
Thanks for reporting this. This is a bug in the rolling Flat file sink. We have this issue covered in the other sinks ( like the azure table sink and sql sink ) where we drop events once we hit a threshold and we cannot write to the destination. However this fix doe not make it into the rolling flat file sink in time. You do have the ability to purge old entries in the rolling flat file sink so that you do not hit this condition under most normal circumstances. Here is a link to code snippet on diagnosing internal slab errors: http://stackoverflow.com/questions/30644279/why-slab-sqldatabasesink-stopped-writing-to-traces-table
In your case we should be raising a  SemanticLoggingEventSource.Log.RollingFlatFileSinkWriteFailed event.

**Comment by svestin** [comment]
Thank you for the reply!

I will wait until the bug is fixed before putting SLAB into production environment.

I looked at the link provided on how to get the internal events generated by SLAB, however in my “Out-Of-Disk-Space”-scenario I guess it will do no good, to try to use a sink that writes to file (as the disk is full :-) ).

So, I would very much appreciate some expert opinions on how to manage SLAB internal errors in my application (e.g. in a client application: show a dialog that states that the disk is full and no more logs will be written).
I see these possible solutions:

Solution 1:
Add a new computer to the production environment. Install a SQL-server on the new computer. Use the sql-sink and log SLAB internal events. Let my application regularly poll the sql-server for new events. Let my application perform different actions depending of the internal SLAB-events generated (e.g. the disk is full). I do not think my customer will accept this solution.

Solution 2:
Create your own RAM-sink and configure it to listen to SLAB internal events. Let this special sink perform any actions needed by my application depending on the event. It feels like quite a big “round-trip” for SLAB internal event, passing it to a EventSource  (and ETW?) before getting it back to the application. Is this the way to go?

Solution 3:
Make a wish for some enhancement and new features in SLAB. It would be so simple to use, if there were a regular .net-event (MulticastDelegate) fired for every ETW-event defined in SemanticLoggingEventSource. Possibly this would break design on a higher architectural level, but some simple in-process error handling would be very nice to have. A quick look into the code states that “SemanticLoggingEventSource” is sealed and that the static property “Log” is ReadOnly so I guess that customization of “SemanticLoggingEventSource” is out of the question?

Solution 4:
Any new ideas are very welcome :-)

Best Regards
 /Stefan Vestin

**Comment by manikrish** [comment]
Hi Stefan,

For a desktop app you could make use of a custom in-memory sink, as you mentioned, since the goal is to show a prompt to the user. There is no roundtrip if you are using SLAB in-process since you are bypassing ETW when using the block in process. This is the quickest and easiest route and should work well. 

For a server application you would write to a remote sink or a sink which raises an alert (like send an email to the operator). 

A 3rd option could be to make use of Reactive extensions. If you are not familiar with Rx there is a bit of a learning curve and on the surface it seems like a lot of work to get your scenario working. However, I just thought it would be worth mentioning. You can add a filter for the semantic logging event source which filters out errors you are interested in and either raises an alert which gets dispatched to the Ux which shows the prompt. There are samples which shows how slab integrates with Rx and you can use this as a starting point if you want to check out if this approach will work for you. 
Sample is at: https://github.com/mspnp/semantic-logging/tree/master/quickstarts

Mani

**Comment by svestin** [comment]
Tanks for the quick answer!
I will create an in-memory sink and create a parser for the events to be able to perform the actions I’m interested in. It will solve my problems for now :-)
Thanks again!!!

Some reflections:
As a user of SLAB, I do think it would be more intuitive, more robust and more easy to use if the design included some kind of error handling. After another quick look into the code, I guess that the lack of error handling in SLAB is inherited from the lack of error handling in the EventSource class.
I just returned to the .Net environment after spending some years working with critical software running on RTOS and DO-178B. So I guess that I probably have an “unhealthy” focus on robustness :-)

I do like the idea that code libraries should have proper error handling and also possibly some logging for convenience, rather than only support logging and then it is up the code using the library to parse the log for proper error handling.

To conclude, what to do, to get robust logging with SLAB:
* Every user of SLAB should create an in-memory sink do listen for internal events generated by the SemanticLoggingEventSource class.
* Create a simple event-parser for SLAB events to filter out important events and make it possible to perform necessary actions.
* Expect that events picked up by the in-memory sink could be executed on another thread. (correct?)
* When new versions of SLAB are released, ALWAYS walk thru ALL the events in the SemanticLoggingEventSource class to verify that already existing eventIDs have the same meaning as before and locate new eventIDs that must be handled by the event-parser. (To keep code clean, also locate any removed eventIDs).
* If an asynchronous sink is used (e.g. RollingFlatFile), there is no way of knowing if the internal worker thread actually is alive (and that the logs are actually written to file). I don’t think there is any internal SLAB-event written (at the moment), if the worker thread terminates (for any reason), so it will not be possible to use the in-memory sink to catch this error.  If the log is really important, you have to actually check in the file system to verify that important information is actually written.

Have I missed anything?

Best Regards
/Stefan Vestin

PS. “Reactive Extensions” looks interesting. I will take a closer look at it! :-) DS.

**Comment by manikrish** [comment]
hi Stefan,
The link below has hands on labs on writing a custom sink. you will get the event data in a structure which you can use to filter any internal errors you are interested in. 
The labs may be a bit out of date but should still help to get started. 
http://www.microsoft.com/en-us/download/confirmation.aspx?id=40286

Mani

**Comment by manikrish** [comment]
@svestin When you run out of disk space the workarounds are: 
1. For a server app - send a notification to operator that logs are not being processed so that he can take remedial action using a custom sink ( sending an e-mail for application). 
2. For desktop app inform the user. 
For both 1 and 2 above you can use a custom sink. Other alternatives are discussed in this issue thread. 
I am closing this particular issue and opening another bug to track the out-of-memory issue.

**Comment by manikrish** [comment]
Opened a new issue which describes work required to fix this across all sinks: https://github.com/mspnp/semantic-logging/issues/35
Closing this.
