### ISSUE TITLE
SQL Database Sink stripping the contents of Payload and FormattedMessage columns after 4000 characters

### ISSUE THREAD

**Issue by skamati** [mspnp/semantic-logging#68]
SQL database sink is stripping the contents of Payload and FormattedMessage column in database after 4000 characters.
When looked at the source code of the sink, it is evident that these column lengths have been capped to 4000 characters. 
1. Any idea why there is such a limitation on the number of characters?

In our application, when the payload and/or FormattedMessage is of greater than 4000 characters, the same is being trimmed and logged in the database table.

1. Is there workaround for this one? And can we update the source code to log more than 4000 characters?

**Comment by mekoda** [comment]
Hi @skamati, 

It's a design decision, feel free to modify the source code to suit your need. However, have in mind the following:

- ETW has a limit of ~64kb in the overall size of its events.
- If the SQL Server table schema is changed in order to have a NVARCHAR bigger than 4000 chars, then the field will be storing not the value but a reference to it, and another table to store the value will be created. This is transparent at the eyes of the user, but it's good to have it in mind.

Share your findings if you decide to change the schema, that will be great.
