### ISSUE TITLE
setup appveyor build

### ISSUE THREAD

**Issue by bennage** [mspnp/semantic-logging#8]

**Comment by richardszalay** [comment]
I've taken a stab at getting this going ([link](https://ci.appveyor.com/project/richardszalay/semantic-logging)), but it looks like some of the unit tests have some timing issues that are exacerbated by the lower spec machines provided by appveyor.

Here are the tests that are failing:

* EventEntrySubjectFixture.ShouldCallOnCompletedInParallel
* sql_db_sink_given_configuration.when_cannot_connect_to_database_then_flush_should_finish_faulted
* sql_db_sink_given_configuration.when_cannot_connect_to_database_then_on_completed_should_not_stall_or_throw
* EventTextFormatterTests.WritesEventData
* EventTextFormatterTests.WritesDetailedOnEventLevel

Oddly, the tests that consistently fail on my local machine (#29 and #30), are fine on appveyor.

**Comment by richardszalay** [comment]
Investigating further, I think that EventEntrySubjectFixture.ShouldCallOnCompletedInParallel should be rewritten as it currently has some serious assumptions around task completion speed.

**Comment by smomilus** [comment]
Hi Richard,
I am currently working on my personal repo to replace test framework with NUnit and streamline all the test fixtures to use Fluent API to build SUT rather than base on inherited object state to avoid corruption.
When I can partially agree with timing issues, I've also noticed problems with Race Condition which occurs in some areas of SLAB. It is difficult to notice this when all the test classes are really huge but it becomes evident when fixtures are split among smaller classes. I think InMemoryTestListener should be rewritten - placing Thread.Sleep(1) reveals race condition where e.g.:

Assert.AreEqual(2, _listener.EventWrittenCount);

returns true if test method runs in isolation
returns false when entire fixture is executed
returns true when entire fixture is executed but Thread.Sleep(1) is invoked
returns true when test method runs through debugger

Thanks

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
