### ISSUE TITLE
Promote supplementary projects

### ISSUE THREAD

**Issue by bennage** [mspnp/semantic-logging#92]
We'd like to compile a list of supplementary projects and include them in the readme. I assume that this will primarily be sinks, but we are open to recommendations.
Please comment on this issue with any recommendations.

**Comment by Expecho** [comment]
**SemanticLogging.EventHub** 
The SemanticLogging.EventHub project provides sinks for the Semantic Logging Application Block that exposes Event Source events to an Azure Event Hub. There is an HTTPS based sink and an AMQP based sink.

https://github.com/DeHeerSoftware/SemanticLogging.EventHub

**SemanticLogging.Database.Xml** 
SemanticLogging.Database.Xml is a sink for the Semantic Logging Application Block that exposes Event Source events to an Sql Server database. The payload data is stored in an xml document instead of a Json document using an xml type column.

https://github.com/DeHeerSoftware/SemanticLogging.Database.Xml

**Comment by bennage** [comment]
I just learned about:
https://github.com/ohadschn/et4w

**Comment by robichaud** [comment]
Application Insights for Semantic Logging:
[https://github.com/fidmor89/SLAB_AppInsights](https://github.com/fidmor89/SLAB_AppInsights)

**Comment by bdongus** [comment]
Not mine, but an alternative to et4w: https://github.com/jonwagner/EventSourceProxy

**Comment by bennage** [comment]
Please see the note on #91. We are no longer working on Semantic Logging.
